/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.27).
 * https://github.com/swagger-api/swagger-codegen Do not edit the class manually.
 */
package se.bjurr.springrestclient.test.requestmapping.spec.api;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@RequestMapping("/base")
public interface MixedUseCasesApi {

  @RequestMapping(value = "/doget/{theId}", method = RequestMethod.GET)
  ResponseEntity<Void> doGetNoNameInPathVariable(@PathVariable Long theId);

  @RequestMapping(path = "/doget/{theId}", method = RequestMethod.GET)
  ResponseEntity<Void> doGetPath(@PathVariable("theId") Long theId);

  @RequestMapping(method = RequestMethod.GET)
  void doGetNoPath();

  @RequestMapping(path = "/", method = RequestMethod.GET)
  void doGetSlashPath();
}
